FROM continuumio/miniconda3

WORKDIR /app

COPY environment.yml .

RUN conda env create -f environment.yml && conda clean -a

SHELL ["conda", "run", "-n", "fastapi-backend-3", "/bin/bash", "-c"]

COPY . /app

RUN apt-get update && apt-get install -y \
    wget \
    libgtk-3-0 \
    libnss3 \
    libnspr4 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libdrm2 \
    libgbm1 \
    libasound2 \
    curl \
    xvfb

RUN playwright install --with-deps

ENV PATH /opt/conda/envs/fastapi-backend-3/bin:$PATH

EXPOSE 8000

RUN echo "#!/bin/bash" > start.sh && \
    echo "source activate fastapi-backend-3" >> start.sh && \
    echo "xvfb-run --auto-servernum --server-num=1 uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug" >> start.sh && \
    chmod +x start.sh

CMD ["./start.sh"]